config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'
  resources :books, :only => :index
  get 'books/with_quantity'
  resources :shops, :only => [:index, :show]

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :book
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :stock

  scope :order_by_id, -> { order(:id) }
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :stock
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :shop
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.includes(:author).order("authors.name").order_by_id
  end

  def with_quantity
    @stocks = Stock.includes(:book).group("books.id", "books.title").order("sum(quantity) desc" ,"books.id").sum("quantity")
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/index.html.erb
<h1>Books</h1>
<%= link_to 'home', welcome_index_path %><br /><br />
<table border="1">
  <tr>
    <th>book id</th>
    <th>title</th>
    <th>author</th>
    <th>author id</th>
  </tr>

  <% @books.each do |book| %>
  <tr>
    <td><%= book.id %></td>
    <td><%= book.title %></td>
    <td><%= book.author.name %></td>
    <td><%= book.author.id %></td>
  </tr>
  <% end %>
</table>

app/views/books/with_quantity.html.erb
<h1>Books with quantity amoung all shops</h1>
<%= link_to 'home', welcome_index_path %><br /><br />
<table border="1">
  <tr>
    <th>book id</th>
    <th>title</th>
    <th>quantity</th>
  </tr>

  <% @stocks.each do |stock| %>
  <tr>
    <td><%= stock[0][0] %></td>
    <td><%= stock[0][1] %></td>
    <td><%= stock[1] %></td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4test</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shops/index.html.erb
<h1>Shops</h1>
<%= link_to 'home', welcome_index_path %><br />
<ul>
  <% @shops.each do |shop| %>
  <li><%= link_to(shop.name, shop_path(shop)) %></li>
  <% end %>
</ul>

app/views/shops/show.html.erb
<h1><%= @shop.name %></h1>
<%= link_to 'home', welcome_index_path %> &gt;&gt; <%= link_to 'Shops', shops_path %><br /><br />


<table border="1">
  <tr>
    <th>id</th>
    <th>title</th>
    <th>author</th>
    <th>author id</th>
    <th>quantity</th>
  </tr>

  <% @shop.stock.includes(book: :author).order("books.title").each do |stock| %>

  <tr>
    <td><%= stock.id %></td>
    <td><%= stock.book.title %></td>
    <td><%= stock.book.author.name %></td>
    <td><%= stock.book.author.id %></td>
    <td><%= stock.quantity %></td>
  </tr>

  <% end %>

</table>

app/views/welcome/index.html.erb
<h1>書店トップページ</h1>
<%= link_to 'Books', books_path %><br />
<%= link_to 'Shops', shops_path %><br />
<%= link_to 'Books with quantity among all shops', books_with_quantity_path %><br />